### ISSUE TITLE
most compatible implementation of yolov3 tensorflow

### ISSUE THREAD

**Issue by wiamadaya** [peace195/tensorflow-lite-yolo-v3#10]
Hi,

I would like to know your recommendation on which implementation is the most compatible with your yolov3-tf to tflite conversion, i am aware of the following, please let me know if you have others

https://github.com/YunYang1994/tensorflow-yolov3 ? https://github.com/AlexeyAB/darknet ?

**Comment by peace195** [comment]
@wiamadaya  https://github.com/AlexeyAB/darknet . Thanks 👍
