### ISSUE TITLE
Op builtin_code out of range: 97.

### ISSUE THREAD

**Issue by nscotto** [peace195/tensorflow-lite-yolo-v3#2]
This might be a version compatibility, but any help is appreciated as I can't find the resources to solve it,

After trying to run a simple app using the tflite converted model, I get this error:

```
Op builtin_code out of range: 97. Are you using old TFlite binary with newer model?
```

Thanks in advance.

**Comment by peace195** [comment]
Hi @nscotto. Could you share your environment, code for reading tflite and the full error traceback?

It will help me a lot.

**Comment by nscotto** [comment]
Sadly I am using a benchmark app that I didn't make, it was meant to be compatible with tensorflow 1.12 so that may be the issue.
Otherwise the network seem to be good, I just don't have another code available to test it.
It's probably best to close the issue since it is not really related to your repos, sorry for the annoyance.
