### ISSUE TITLE
custom .cfg file

### ISSUE THREAD

**Issue by ambr89** [peace195/tensorflow-lite-yolo-v3#4]
Hi!

What's happened if I've trained my tiny yolo v3 with a custom setting in .cfg file?

I've change width and height, I've change anchor and threshold.

**Comment by kuailink** [comment]
Hi, I want to ask the same/similar question. I trained my own dataset based on yolov3-tiny.cfg but with some minor tweaks: I only changed the number of `classes` (1 in my case) and `filters` ( 18 in my case) accordingly. Do I need to change any code?

I ran commands per instructions and it seemed to finish successfully and a file `yolo_v3.tflite` was generated. But I still want to ask this question to ensure I did it correctly.

PS: I've tried almost every project on github about converting yolov3 models to tensorflow (lite), and this is the only one that works for me (although pending on my further testing). Thanks!

**Comment by peace195** [comment]
@kuailink You only need to change the `coco.names` file.

**Comment by kuailink** [comment]
@peace195 Perfect! Yes, I did replace it with my content. Thanks for your repo again!

**Comment by peace195** [comment]
@ambr89 
https://github.com/peace195/tensorflow-lite-yolo-v3/blob/master/yolo_v3.py#L12
https://github.com/peace195/tensorflow-lite-yolo-v3/blob/master/convert_weights_pb.py#L26
