### ISSUE TITLE
Any working example on yolov3 models used by tensorflow lite?

### ISSUE THREAD

**Issue by kuailink** [peace195/tensorflow-lite-yolo-v3#5]
I'm sorry if this sounds like a stupid question, but does tensorflow lite even support yolov3 models? I have migrated the model to .tflite format, but I haven't found a working example. All examples that I can find are all using yolov2. It would be very helpful is an example for iOS and/or Android can be provided. A link is also OK.

**Comment by peace195** [comment]
@kuailink My suggestion: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java

But you can write your own code. It is good for you. When you finish it, please share to the community 👏
