### ISSUE TITLE
Mistake in the environment setup

### ISSUE THREAD

**Issue by titanbender** [peace195/tensorflow-lite-yolo-v3#7]
Thanks for your work! 

When running the docker setup there seems to be a difference in the path and the actual repository name: 

"tensorflow-lite-yolo-v3" should be changed to "tensorflow-lite-YOLOv3" 

Please let me know if that makes sense.

**Comment by peace195** [comment]
@titanbender Yes, please change it. I forgot to update the readme when changing the repo's name.
